### ISSUE TITLE
Docker build failing 

### ISSUE THREAD

**Issue by AdheipSingh** [wikimedia/operations-software-druid_exporter#17]
running docker build failing
```
Sending build context to Docker daemon  246.8kB
Step 1/9 : ARG BASE_IMAGE=python:3.8-alpine
Step 2/9 : FROM $BASE_IMAGE
 ---> fbfb63e3c6bb
Step 3/9 : COPY conf/ /exporter/conf/
 ---> 95748d6954b9
Step 4/9 : COPY druid_exporter/ /exporter/druid_exporter/
 ---> 3a630da51f3f
Step 5/9 : COPY setup.py /exporter/setup.py
 ---> 2d08d84b5db3
Step 6/9 : WORKDIR /exporter
 ---> Running in 7345692ca9a2
Removing intermediate container 7345692ca9a2
 ---> 17154efd2415
Step 7/9 : RUN python ./setup.py install
 ---> Running in 103cf7c784f7
running install
running bdist_egg
running egg_info
creating druid_exporter.egg-info
writing druid_exporter.egg-info/PKG-INFO
writing dependency_links to druid_exporter.egg-info/dependency_links.txt
writing entry points to druid_exporter.egg-info/entry_points.txt
writing requirements to druid_exporter.egg-info/requires.txt
writing top-level names to druid_exporter.egg-info/top_level.txt
writing manifest file 'druid_exporter.egg-info/SOURCES.txt'
reading manifest file 'druid_exporter.egg-info/SOURCES.txt'
writing manifest file 'druid_exporter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/druid_exporter
copying druid_exporter/collector.py -> build/lib/druid_exporter
copying druid_exporter/exporter.py -> build/lib/druid_exporter
copying druid_exporter/__init__.py -> build/lib/druid_exporter
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/druid_exporter
copying build/lib/druid_exporter/collector.py -> build/bdist.linux-x86_64/egg/druid_exporter
copying build/lib/druid_exporter/exporter.py -> build/bdist.linux-x86_64/egg/druid_exporter
copying build/lib/druid_exporter/__init__.py -> build/bdist.linux-x86_64/egg/druid_exporter
byte-compiling build/bdist.linux-x86_64/egg/druid_exporter/collector.py to collector.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/druid_exporter/exporter.py to exporter.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/druid_exporter/__init__.py to __init__.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying druid_exporter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying druid_exporter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying druid_exporter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying druid_exporter.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying druid_exporter.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying druid_exporter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/druid_exporter-0.10-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing druid_exporter-0.10-py3.8.egg
Copying druid_exporter-0.10-py3.8.egg to /usr/local/lib/python3.8/site-packages
Adding druid-exporter 0.10 to easy-install.pth file
Installing druid_exporter script to /usr/local/bin

Installed /usr/local/lib/python3.8/site-packages/druid_exporter-0.10-py3.8.egg
Processing dependencies for druid-exporter==0.10
Searching for gevent
Reading https://pypi.org/simple/gevent/
Downloading https://files.pythonhosted.org/packages/8e/f3/434c06bd285ce52a859a7239b7f03d8e02d49f4f39c7cc25536f39d7e4b1/gevent-20.6.2.tar.gz#sha256=a23c2abf08e851c988723f6a2996d495f513a2c0dc70f9956af03af8debdb5d1
Best match: gevent 20.6.2
Processing gevent-20.6.2.tar.gz
Writing /tmp/easy_install-r946xaad/gevent-20.6.2/setup.cfg
Running gevent-20.6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r946xaad/gevent-20.6.2/egg-dist-tmp-1xdw8t_y
/usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'cffi_modules'
  warnings.warn(msg)
warning: no files found matching 'changelog.rst'
warning: no files found matching 'Makefile.ext'
warning: no files found matching 'known_failures.py'
warning: no files found matching '.pep8'
no previously-included directories found matching '*/__pycache__'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.lo' found anywhere in distribution
warning: no previously-included files matching '*.la' found anywhere in distribution
warning: no previously-included files matching '.dirstamp' found anywhere in distribution
warning: no previously-included files matching 'config.log' found anywhere in distribution
warning: no previously-included files matching 'config.status' found anywhere in distribution
warning: no previously-included files matching 'config.cache' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.coverage' found under directory 'src/greentest'
no previously-included directories found matching 'src/greentest/htmlcov'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/c-ares'
warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps/c-ares'
warning: no previously-included files matching '_corecffi.c' found under directory 'src/gevent'
warning: no previously-included files found matching 'configure-output'
warning: no previously-included files found matching 'configure-output.txt'
warning: no previously-included files found matching 'deps/TAGS'
warning: no previously-included files found matching 'deps/c-ares/ares_build.h'
warning: no previously-included files found matching 'deps/c-ares/ares_config.h'
warning: no previously-included files found matching 'deps/c-ares/libcares.pc'
warning: no previously-included files found matching 'deps/c-ares/libtool'
warning: no previously-included files found matching 'deps/c-ares/Makefile'
no previously-included directories found matching 'deps/c-ares/.deps'
no previously-included directories found matching 'deps/c-ares/.libs'
no previously-included directories found matching 'deps/libev/.deps'
no previously-included directories found matching 'deps/libev/.libs'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libev'
warning: no previously-included files matching 'libtool' found under directory 'deps/libev'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/libev'
warning: no previously-included files matching 'config.h' found under directory 'deps/libev'
no previously-included directories found matching 'deps/libuv/.deps'
no previously-included directories found matching 'deps/libuv/.libs'
no previously-included directories found matching 'deps/libuv/src/.deps'
no previously-included directories found matching 'deps/libuv/src/unix/.deps'
no previously-included directories found matching 'deps/libuv/src/win/.deps'
no previously-included directories found matching 'deps/libuv/test/.deps'
no previously-included directories found matching 'deps/libuv/autom4te.cache'
no previously-included directories found matching 'deps/libuv/m4'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libuv'
warning: no previously-included files matching 'Makefile.in' found under directory 'deps/libuv'
warning: no previously-included files matching 'ar-lib' found under directory 'deps/libuv'
warning: no previously-included files matching 'aclocal.m4' found under directory 'deps/libuv'
warning: no previously-included files matching 'compile' found under directory 'deps/libuv'
warning: no previously-included files matching 'configure' found under directory 'deps/libuv'
warning: no previously-included files matching 'depcomp' found under directory 'deps/libuv'
warning: no previously-included files matching 'install-sh' found under directory 'deps/libuv'
warning: no previously-included files matching 'libtool' found under directory 'deps/libuv'
warning: no previously-included files matching 'libuv.pc' found under directory 'deps/libuv'
warning: no previously-included files matching 'ltmain.sh' found under directory 'deps/libuv'
warning: no previously-included files matching 'missing' found under directory 'deps/libuv'
Running '(cd  "/tmp/easy_install-r946xaad/gevent-20.6.2/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/easy_install-r946xaad/gevent-20.6.2
configure: error: in `/tmp/easy_install-r946xaad/gevent-20.6.2/deps/libev':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/setup.py", line 471, in <module>
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/setup.py", line 338, in run_setup
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 350, in build_extension
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 347, in gevent_prepare
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuplibev.py", line 55, in configure_libev
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 194, in system
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 190, in _system
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/tmp/easy_install-r946xaad/gevent-20.6.2/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./setup.py", line 3, in <module>
    setup(name='druid_exporter',
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 714, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/setup.py", line 471, in <module>
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/setup.py", line 338, in run_setup
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 350, in build_extension
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 347, in gevent_prepare
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuplibev.py", line 55, in configure_libev
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 194, in system
  File "/tmp/easy_install-r946xaad/gevent-20.6.2/_setuputils.py", line 190, in _system
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/tmp/easy_install-r946xaad/gevent-20.6.2/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1.
The command '/bin/sh -c python ./setup.py install' returned a non-zero code: 1
```

**Comment by freemanlutsk** [comment]
try to use the following Dokerfile:
```
ARG BASE_IMAGE=python:3.8-alpine
FROM $BASE_IMAGE

COPY conf/ /exporter/conf/
COPY druid_exporter/ /exporter/druid_exporter/
COPY setup.py /exporter/setup.py
RUN apk add build-base
WORKDIR /exporter

RUN python ./setup.py install

EXPOSE 8000

ENTRYPOINT ["python", "-u", "druid_exporter/exporter.py"]
```

**Comment by elukey** [comment]
@busecolak if you have time and want to review the new Dockerfiler, I'd be happy!

**Comment by elukey** [comment]
@AdheipSingh sorry I forgot to follow up, is the problem still happening?

**Comment by chrisociepa** [comment]
`RUN apk add build-base` fixes the problem
